language: python
python: 3.5

env:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=flake8

install:
    - pip install tox codecov

script:
    - tox -e ${TOXENV}

after_success:
    - codecov

notifications:
    email: false
