language: python
python: 3.5

env:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=flake8

matrix:
    fast_finish: true

    include:
        - python: "nightly"
          env: TOXENV=py36

    allow_failures:
        - python: "nightly"

install:
    - pip install tox codecov

script:
    - tox -e ${TOXENV}

after_success:
    - codecov

notifications:
    email: false
